export const personalInfo = {
    name: "name",
    avatar: "/images/avatar.jpg",
    education: ["education.ntnu", "education.iii"],
    projects: {
        experience: [
            "basicInfoProjects.budget",
            "basicInfoProjects.eeSystem",
            "basicInfoProjects.factory",
            "basicInfoProjects.inventory",
            "basicInfoProjects.coffee",
            "basicInfoProjects.overwatch",
            "basicInfoProjects.asus",
        ],
        items: [
            {
                id: 1,
                image: "/images/vue_cart.png",
                alt: "vue cart",
                link: "https://github.com/iona0511/coffee_project",
                title: "projects.items.asus.title",
                content: "projects.items.asus.content",
                tags: ["Vue", "php", "MySQL"],
            },
            {
                id: 2,
                image: "/images/scroll_animatiom.png",
                alt: "scroll animation",
                link: "https://hunter850.github.io/scroll_animation/",
                title: "projects.items.scrollAnimation.title",
                content: "projects.items.scrollAnimation.content",
                tags: ["JavaScript", "Bootstrap"],
            },
            {
                id: 3,
                image: "/images/asus_slicing_practice.png",
                alt: "ASUS slicing",
                link: "https://hunter850.github.io/slicing_practice/",
                title: "projects.items.asusLayout.title",
                content: "projects.items.asusLayout.content",
                tags: ["HTML", "CSS"],
            },
            {
                id: 4,
                image: "/images/0+b_frontpage.png",
                alt: "0+b coffee",
                link: "https://project0plusb.netlify.app/",
                title: "projects.items.coffee.title",
                content: "projects.items.coffee.content",
                tags: ["React", "Node", "MySQL"],
            },
            {
                id: 5,
                image: "/images/resume.png",
                alt: "Kevin's resume",
                link: "https://hunter850.github.io/resume/",
                title: "projects.items.resume.title",
                content: "projects.items.resume.content",
                tags: ["React", "SCSS"],
            },
            {
                id: 6,
                image: "/images/ow_slicing_practice.png",
                alt: "overwatch slicing",
                link: "https://hunter850.github.io/slicing_practice_RWD/",
                title: "projects.items.overwatch.title",
                content: "projects.items.overwatch.content",
                tags: ["HTML", "CSS", "JavaScript"],
            },
            {
                id: 7,
                image: "/images/holo_dashboard.jpg",
                alt: "Holo Dashboard",
                link: "https://holo-board.hlkw.me/",
                title: "projects.items.holoDashboard.title",
                content: "projects.items.holoDashboard.content",
                tags: ["Nextjs", "Tailwind CSS", "Express", "Cheerio"],
            },
            {
                id: 8,
                image: "/images/open_graph.jpg",
                alt: "Kevin | blog",
                link: "https://hlkw.me/zh-TW",
                title: "projects.items.newResume.title",
                content: "projects.items.newResume.content",
                tags: ["Nextjs", "Tailwind CSS", "shadcn", "next-intl"],
            },
        ],
    },
    skills: [
        {
            id: 1,
            img: "/images/html_css_js.png",
            imgDescription: "html css and javascript",
            title: "skills.htmlCssJs.title",
            content: ["skills.htmlCssJs.items.0", "skills.htmlCssJs.items.1"],
        },
        {
            id: 2,
            img: "/images/vuejs_logo.png",
            imgDescription: "vuejs logo",
            title: "skills.vue.title",
            content: ["skills.vue.items.0", "skills.vue.items.1"],
        },
        {
            id: 3,
            img: "/images/react.png",
            imgDescription: "react logo",
            title: "skills.react.title",
            content: ["skills.react.items.0", "skills.react.items.1", "skills.react.items.2"],
        },
        {
            id: 4,
            img: "/images/git.png",
            imgDescription: "git and github logo",
            title: "skills.git.title",
            content: ["skills.git.items.0", "skills.git.items.1", "skills.git.items.2"],
        },
        {
            id: 5,
            img: "/images/backend.png",
            imgDescription: "node, mariadb and express logo",
            title: "skills.backend.title",
            content: ["skills.backend.items.0", "skills.backend.items.1"],
        },
        {
            id: 6,
            img: "/images/sc_tw_mui.png",
            imgDescription: "styled-components, Tailwind CSS, Material UI logo",
            title: "skills.uiLibs.title",
            content: ["skills.uiLibs.items.0", "skills.uiLibs.items.1", "skills.uiLibs.items.2"],
        },
    ],
    experiences: [
        {
            id: 1,
            time: "experience.university.time",
            title: "experience.university.title",
            content: "experience.university.content",
        },
        {
            id: 2,
            time: "experience.military.time",
            title: "experience.military.title",
            content: "experience.military.content",
        },
        {
            id: 3,
            time: "experience.career.time",
            title: "experience.career.title",
            content: "experience.career.content",
        },
        {
            id: 4,
            time: "experience.training.time",
            title: "experience.training.title",
            content: "experience.training.content",
        },
        {
            id: 5,
            time: "experience.wiwynn.time",
            title: "experience.wiwynn.title",
            content: "experience.wiwynn.content",
        },
    ],
    contact: {
        email: "hunter850711@gmail.com",
        github: "https://github.com/hunter850",
    },
};
